spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/sm_db
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: Flame+1226

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志控制台输出
  global-config:
    db-config:
      table-prefix: news_
  type-aliases-package: com.entity